export const projects = [
  {
    title: 'F1 HASS site',
    description: "Using HTML, CSS, Javascript I designed a tribute site to the only American team and Formula one racing. It features a responsive header along with a live twitter feed that updates based on key word related to formula one.",
      image: '/images/1.png',
      tags: ['HTML', 'CSS', 'JavaScript',],
    source: 'https://turbo-boat.herokuapp.com/',
    visit: 'https://github.com/DMAN28/turbo-spork',
    id: 0,
  },
  {
    title: 'Note taker App',
    description:"A note taking application that allows the user to take notes label and save them",
    image: '/images/2.png',
    tags: ['HTML', 'CSS', 'JavaScript,'],
    source: 'https://note-t8kr.herokuapp.com/',
    visit: 'https://github.com/DMAN28/note-taker',
    id: 1,
  },
  {
    title: 'CLI crypto app',
    description: "A CLI application that enable s user with a Nomics API key to track top performing crypto assets",
      image: '/images/3.jpg',
      tags: ['Node', 'JavaScript'],
    source: 'hhttps://github.com/DMAN28/super-duper-dollop#readme',
    visit: 'https://github.com/DMAN28/super-duper-dollop',
    id: 2,
  },
  {
    title: 'Scheduler app',
    description: "This planner application was created to give a user the ability to manage and track daily activities.",
    image: '/images/4.jpg',
    tags: ['HTML', 'CSS', 'JavaScript,'],
    source: 'https://dman28.github.io/work-day-scheduler/',
    visit: 'https://github.com/DMAN28/work-day-scheduler',
    id: 3,
  },
  {
    title: 'Learn it',
    description: "This was a team project designed to help users find and share learning resources for computer coding. Interested in learning checkout the site using the following EMAIL: mitts@gmail.com PASSWORD: 123456",
    image: '/images/5.jpg',
    tags: ['JavaScript', 'CSS', 'Node'],
    source: 'https://damp-journey-96412.herokuapp.com/',
    visit: 'https://github.com/DMAN28/learn-code-work',
    id: 4,
  },
  {
    title: 'Beat Hub',
    description: "A platform used to share and discuss music with friends allows the user to login save and comment on albums built with MERN stack. Try it out with this guest log in  EMAIL: mitts@gmail.com PASSWORD: 123456",
    image: '/images/6.png',
    tags: ['React', 'ApolloServer', 'Node' , 'GraphQL'],
    source: 'https://blooming-tundra-89879.herokuapp.com/',
    visit: 'https://github.com/DMAN28/beat-hub',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2021, text: 'Started University of Oregon Full stack web development program', },
  { year: 2022, text: 'Completed Certificate in Full Stack Web Development from The University of Oregon ', },
];